# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake

# The command to remove a file.
RM = /nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huydna/projects/dash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huydna/projects/dash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/ad4c8nx2lkjs4zq0sj9jdpn7w45v9ccs-cmake-3.31.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huydna/projects/dash/CMakeFiles /home/huydna/projects/dash//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huydna/projects/dash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dart-base

# Build rule for target.
dart-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dart-base
.PHONY : dart-base

# fast build rule for target.
dart-base/fast:
	$(MAKE) $(MAKESILENT) -f dart-impl/base/CMakeFiles/dart-base.dir/build.make dart-impl/base/CMakeFiles/dart-base.dir/build
.PHONY : dart-base/fast

#=============================================================================
# Target rules for targets named dart-mpi

# Build rule for target.
dart-mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dart-mpi
.PHONY : dart-mpi

# fast build rule for target.
dart-mpi/fast:
	$(MAKE) $(MAKESILENT) -f dart-impl/mpi/CMakeFiles/dart-mpi.dir/build.make dart-impl/mpi/CMakeFiles/dart-mpi.dir/build
.PHONY : dart-mpi/fast

#=============================================================================
# Target rules for targets named dart-tasking

# Build rule for target.
dart-tasking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dart-tasking
.PHONY : dart-tasking

# fast build rule for target.
dart-tasking/fast:
	$(MAKE) $(MAKESILENT) -f dart-impl/tasking/CMakeFiles/dart-tasking.dir/build.make dart-impl/tasking/CMakeFiles/dart-tasking.dir/build
.PHONY : dart-tasking/fast

#=============================================================================
# Target rules for targets named dash-mpi

# Build rule for target.
dash-mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dash-mpi
.PHONY : dash-mpi

# fast build rule for target.
dash-mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/dash-mpi.dir/build.make dash/CMakeFiles/dash-mpi.dir/build
.PHONY : dash-mpi/fast

#=============================================================================
# Target rules for targets named app.01.mindeg.mpi

# Build rule for target.
app.01.mindeg.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app.01.mindeg.mpi
.PHONY : app.01.mindeg.mpi

# fast build rule for target.
app.01.mindeg.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/app.01.mindeg.mpi.dir/build.make dash/CMakeFiles/app.01.mindeg.mpi.dir/build
.PHONY : app.01.mindeg.mpi/fast

#=============================================================================
# Target rules for targets named bench.01.igups.mpi

# Build rule for target.
bench.01.igups.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.01.igups.mpi
.PHONY : bench.01.igups.mpi

# fast build rule for target.
bench.01.igups.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.01.igups.mpi.dir/build.make dash/CMakeFiles/bench.01.igups.mpi.dir/build
.PHONY : bench.01.igups.mpi/fast

#=============================================================================
# Target rules for targets named bench.02.memhog.mpi

# Build rule for target.
bench.02.memhog.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.02.memhog.mpi
.PHONY : bench.02.memhog.mpi

# fast build rule for target.
bench.02.memhog.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.02.memhog.mpi.dir/build.make dash/CMakeFiles/bench.02.memhog.mpi.dir/build
.PHONY : bench.02.memhog.mpi/fast

#=============================================================================
# Target rules for targets named bench.02.meminit.mpi

# Build rule for target.
bench.02.meminit.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.02.meminit.mpi
.PHONY : bench.02.meminit.mpi

# fast build rule for target.
bench.02.meminit.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.02.meminit.mpi.dir/build.make dash/CMakeFiles/bench.02.meminit.mpi.dir/build
.PHONY : bench.02.meminit.mpi/fast

#=============================================================================
# Target rules for targets named bench.03.gups.mpi

# Build rule for target.
bench.03.gups.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.03.gups.mpi
.PHONY : bench.03.gups.mpi

# fast build rule for target.
bench.03.gups.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.03.gups.mpi.dir/build.make dash/CMakeFiles/bench.03.gups.mpi.dir/build
.PHONY : bench.03.gups.mpi/fast

#=============================================================================
# Target rules for targets named bench.04.histo.mpi

# Build rule for target.
bench.04.histo.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.04.histo.mpi
.PHONY : bench.04.histo.mpi

# fast build rule for target.
bench.04.histo.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.04.histo.mpi.dir/build.make dash/CMakeFiles/bench.04.histo.mpi.dir/build
.PHONY : bench.04.histo.mpi/fast

#=============================================================================
# Target rules for targets named bench.04.histo-tf.mpi

# Build rule for target.
bench.04.histo-tf.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.04.histo-tf.mpi
.PHONY : bench.04.histo-tf.mpi

# fast build rule for target.
bench.04.histo-tf.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.04.histo-tf.mpi.dir/build.make dash/CMakeFiles/bench.04.histo-tf.mpi.dir/build
.PHONY : bench.04.histo-tf.mpi/fast

#=============================================================================
# Target rules for targets named bench.05.array-range.mpi

# Build rule for target.
bench.05.array-range.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.05.array-range.mpi
.PHONY : bench.05.array-range.mpi

# fast build rule for target.
bench.05.array-range.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.05.array-range.mpi.dir/build.make dash/CMakeFiles/bench.05.array-range.mpi.dir/build
.PHONY : bench.05.array-range.mpi/fast

#=============================================================================
# Target rules for targets named bench.05.pattern.mpi

# Build rule for target.
bench.05.pattern.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.05.pattern.mpi
.PHONY : bench.05.pattern.mpi

# fast build rule for target.
bench.05.pattern.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.05.pattern.mpi.dir/build.make dash/CMakeFiles/bench.05.pattern.mpi.dir/build
.PHONY : bench.05.pattern.mpi/fast

#=============================================================================
# Target rules for targets named bench.06.jacobi-1d.mpi

# Build rule for target.
bench.06.jacobi-1d.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.06.jacobi-1d.mpi
.PHONY : bench.06.jacobi-1d.mpi

# fast build rule for target.
bench.06.jacobi-1d.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.06.jacobi-1d.mpi.dir/build.make dash/CMakeFiles/bench.06.jacobi-1d.mpi.dir/build
.PHONY : bench.06.jacobi-1d.mpi/fast

#=============================================================================
# Target rules for targets named bench.07.local-copy.mpi

# Build rule for target.
bench.07.local-copy.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.07.local-copy.mpi
.PHONY : bench.07.local-copy.mpi

# fast build rule for target.
bench.07.local-copy.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.07.local-copy.mpi.dir/build.make dash/CMakeFiles/bench.07.local-copy.mpi.dir/build
.PHONY : bench.07.local-copy.mpi/fast

#=============================================================================
# Target rules for targets named bench.08.min-element.mpi

# Build rule for target.
bench.08.min-element.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.08.min-element.mpi
.PHONY : bench.08.min-element.mpi

# fast build rule for target.
bench.08.min-element.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.08.min-element.mpi.dir/build.make dash/CMakeFiles/bench.08.min-element.mpi.dir/build
.PHONY : bench.08.min-element.mpi/fast

#=============================================================================
# Target rules for targets named bench.08.transform.mpi

# Build rule for target.
bench.08.transform.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.08.transform.mpi
.PHONY : bench.08.transform.mpi

# fast build rule for target.
bench.08.transform.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.08.transform.mpi.dir/build.make dash/CMakeFiles/bench.08.transform.mpi.dir/build
.PHONY : bench.08.transform.mpi/fast

#=============================================================================
# Target rules for targets named bench.09.multi-reader.mpi

# Build rule for target.
bench.09.multi-reader.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.09.multi-reader.mpi
.PHONY : bench.09.multi-reader.mpi

# fast build rule for target.
bench.09.multi-reader.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.09.multi-reader.mpi.dir/build.make dash/CMakeFiles/bench.09.multi-reader.mpi.dir/build
.PHONY : bench.09.multi-reader.mpi/fast

#=============================================================================
# Target rules for targets named bench.10.summa.mpi

# Build rule for target.
bench.10.summa.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.10.summa.mpi
.PHONY : bench.10.summa.mpi

# fast build rule for target.
bench.10.summa.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.10.summa.mpi.dir/build.make dash/CMakeFiles/bench.10.summa.mpi.dir/build
.PHONY : bench.10.summa.mpi/fast

#=============================================================================
# Target rules for targets named bench.11.hdf-io.mpi

# Build rule for target.
bench.11.hdf-io.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.11.hdf-io.mpi
.PHONY : bench.11.hdf-io.mpi

# fast build rule for target.
bench.11.hdf-io.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.11.hdf-io.mpi.dir/build.make dash/CMakeFiles/bench.11.hdf-io.mpi.dir/build
.PHONY : bench.11.hdf-io.mpi/fast

#=============================================================================
# Target rules for targets named bench.12.for_each.mpi

# Build rule for target.
bench.12.for_each.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.12.for_each.mpi
.PHONY : bench.12.for_each.mpi

# fast build rule for target.
bench.12.for_each.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.12.for_each.mpi.dir/build.make dash/CMakeFiles/bench.12.for_each.mpi.dir/build
.PHONY : bench.12.for_each.mpi/fast

#=============================================================================
# Target rules for targets named bench.13.allreduce.mpi

# Build rule for target.
bench.13.allreduce.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.13.allreduce.mpi
.PHONY : bench.13.allreduce.mpi

# fast build rule for target.
bench.13.allreduce.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.13.allreduce.mpi.dir/build.make dash/CMakeFiles/bench.13.allreduce.mpi.dir/build
.PHONY : bench.13.allreduce.mpi/fast

#=============================================================================
# Target rules for targets named bench.13.taskbench.mpi

# Build rule for target.
bench.13.taskbench.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.13.taskbench.mpi
.PHONY : bench.13.taskbench.mpi

# fast build rule for target.
bench.13.taskbench.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.13.taskbench.mpi.dir/build.make dash/CMakeFiles/bench.13.taskbench.mpi.dir/build
.PHONY : bench.13.taskbench.mpi/fast

#=============================================================================
# Target rules for targets named bench.14.accumulate.mpi

# Build rule for target.
bench.14.accumulate.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.14.accumulate.mpi
.PHONY : bench.14.accumulate.mpi

# fast build rule for target.
bench.14.accumulate.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.14.accumulate.mpi.dir/build.make dash/CMakeFiles/bench.14.accumulate.mpi.dir/build
.PHONY : bench.14.accumulate.mpi/fast

#=============================================================================
# Target rules for targets named bench.15.amsgqbench.mpi

# Build rule for target.
bench.15.amsgqbench.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.15.amsgqbench.mpi
.PHONY : bench.15.amsgqbench.mpi

# fast build rule for target.
bench.15.amsgqbench.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.15.amsgqbench.mpi.dir/build.make dash/CMakeFiles/bench.15.amsgqbench.mpi.dir/build
.PHONY : bench.15.amsgqbench.mpi/fast

#=============================================================================
# Target rules for targets named bench.15.amsgqbench-omp.mpi

# Build rule for target.
bench.15.amsgqbench-omp.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.15.amsgqbench-omp.mpi
.PHONY : bench.15.amsgqbench-omp.mpi

# fast build rule for target.
bench.15.amsgqbench-omp.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.15.amsgqbench-omp.mpi.dir/build.make dash/CMakeFiles/bench.15.amsgqbench-omp.mpi.dir/build
.PHONY : bench.15.amsgqbench-omp.mpi/fast

#=============================================================================
# Target rules for targets named bench.15.copy.mpi

# Build rule for target.
bench.15.copy.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench.15.copy.mpi
.PHONY : bench.15.copy.mpi

# fast build rule for target.
bench.15.copy.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/bench.15.copy.mpi.dir/build.make dash/CMakeFiles/bench.15.copy.mpi.dir/build
.PHONY : bench.15.copy.mpi/fast

#=============================================================================
# Target rules for targets named ex.01.hello.mpi

# Build rule for target.
ex.01.hello.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.01.hello.mpi
.PHONY : ex.01.hello.mpi

# fast build rule for target.
ex.01.hello.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.01.hello.mpi.dir/build.make dash/CMakeFiles/ex.01.hello.mpi.dir/build
.PHONY : ex.01.hello.mpi/fast

#=============================================================================
# Target rules for targets named ex.01.hello-mpi.mpi

# Build rule for target.
ex.01.hello-mpi.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.01.hello-mpi.mpi
.PHONY : ex.01.hello-mpi.mpi

# fast build rule for target.
ex.01.hello-mpi.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.01.hello-mpi.mpi.dir/build.make dash/CMakeFiles/ex.01.hello-mpi.mpi.dir/build
.PHONY : ex.01.hello-mpi.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array.mpi

# Build rule for target.
ex.02.array.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array.mpi
.PHONY : ex.02.array.mpi

# fast build rule for target.
ex.02.array.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array.mpi.dir/build.make dash/CMakeFiles/ex.02.array.mpi.dir/build
.PHONY : ex.02.array.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array-copy.mpi

# Build rule for target.
ex.02.array-copy.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array-copy.mpi
.PHONY : ex.02.array-copy.mpi

# fast build rule for target.
ex.02.array-copy.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array-copy.mpi.dir/build.make dash/CMakeFiles/ex.02.array-copy.mpi.dir/build
.PHONY : ex.02.array-copy.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array-csr.mpi

# Build rule for target.
ex.02.array-csr.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array-csr.mpi
.PHONY : ex.02.array-csr.mpi

# fast build rule for target.
ex.02.array-csr.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array-csr.mpi.dir/build.make dash/CMakeFiles/ex.02.array-csr.mpi.dir/build
.PHONY : ex.02.array-csr.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array-ctors.mpi

# Build rule for target.
ex.02.array-ctors.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array-ctors.mpi
.PHONY : ex.02.array-ctors.mpi

# fast build rule for target.
ex.02.array-ctors.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array-ctors.mpi.dir/build.make dash/CMakeFiles/ex.02.array-ctors.mpi.dir/build
.PHONY : ex.02.array-ctors.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array-delayed.mpi

# Build rule for target.
ex.02.array-delayed.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array-delayed.mpi
.PHONY : ex.02.array-delayed.mpi

# fast build rule for target.
ex.02.array-delayed.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array-delayed.mpi.dir/build.make dash/CMakeFiles/ex.02.array-delayed.mpi.dir/build
.PHONY : ex.02.array-delayed.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.array-local.mpi

# Build rule for target.
ex.02.array-local.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.array-local.mpi
.PHONY : ex.02.array-local.mpi

# fast build rule for target.
ex.02.array-local.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.array-local.mpi.dir/build.make dash/CMakeFiles/ex.02.array-local.mpi.dir/build
.PHONY : ex.02.array-local.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.halo-swap.mpi

# Build rule for target.
ex.02.halo-swap.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.halo-swap.mpi
.PHONY : ex.02.halo-swap.mpi

# fast build rule for target.
ex.02.halo-swap.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.halo-swap.mpi.dir/build.make dash/CMakeFiles/ex.02.halo-swap.mpi.dir/build
.PHONY : ex.02.halo-swap.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix.mpi

# Build rule for target.
ex.02.matrix.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix.mpi
.PHONY : ex.02.matrix.mpi

# fast build rule for target.
ex.02.matrix.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix.mpi.dir/build
.PHONY : ex.02.matrix.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix-multiply.mpi

# Build rule for target.
ex.02.matrix-multiply.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix-multiply.mpi
.PHONY : ex.02.matrix-multiply.mpi

# fast build rule for target.
ex.02.matrix-multiply.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix-multiply.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix-multiply.mpi.dir/build
.PHONY : ex.02.matrix-multiply.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix.halo.heat_equation.mpi

# Build rule for target.
ex.02.matrix.halo.heat_equation.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix.halo.heat_equation.mpi
.PHONY : ex.02.matrix.halo.heat_equation.mpi

# fast build rule for target.
ex.02.matrix.halo.heat_equation.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix.halo.heat_equation.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix.halo.heat_equation.mpi.dir/build
.PHONY : ex.02.matrix.halo.heat_equation.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix.halo.heat_equation.dashtasks.mpi

# Build rule for target.
ex.02.matrix.halo.heat_equation.dashtasks.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix.halo.heat_equation.dashtasks.mpi
.PHONY : ex.02.matrix.halo.heat_equation.dashtasks.mpi

# fast build rule for target.
ex.02.matrix.halo.heat_equation.dashtasks.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix.halo.heat_equation.dashtasks.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix.halo.heat_equation.dashtasks.mpi.dir/build
.PHONY : ex.02.matrix.halo.heat_equation.dashtasks.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi

# Build rule for target.
ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi
.PHONY : ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi

# fast build rule for target.
ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi.dir/build
.PHONY : ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix_distribution_patterns.mpi

# Build rule for target.
ex.02.matrix_distribution_patterns.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix_distribution_patterns.mpi
.PHONY : ex.02.matrix_distribution_patterns.mpi

# fast build rule for target.
ex.02.matrix_distribution_patterns.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix_distribution_patterns.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix_distribution_patterns.mpi.dir/build
.PHONY : ex.02.matrix_distribution_patterns.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix_global_access.mpi

# Build rule for target.
ex.02.matrix_global_access.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix_global_access.mpi
.PHONY : ex.02.matrix_global_access.mpi

# fast build rule for target.
ex.02.matrix_global_access.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix_global_access.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix_global_access.mpi.dir/build
.PHONY : ex.02.matrix_global_access.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix_printed_in_different_ways.mpi

# Build rule for target.
ex.02.matrix_printed_in_different_ways.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix_printed_in_different_ways.mpi
.PHONY : ex.02.matrix_printed_in_different_ways.mpi

# fast build rule for target.
ex.02.matrix_printed_in_different_ways.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix_printed_in_different_ways.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix_printed_in_different_ways.mpi.dir/build
.PHONY : ex.02.matrix_printed_in_different_ways.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.matrix_views.mpi

# Build rule for target.
ex.02.matrix_views.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.matrix_views.mpi
.PHONY : ex.02.matrix_views.mpi

# fast build rule for target.
ex.02.matrix_views.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.matrix_views.mpi.dir/build.make dash/CMakeFiles/ex.02.matrix_views.mpi.dir/build
.PHONY : ex.02.matrix_views.mpi/fast

#=============================================================================
# Target rules for targets named ex.02.unordered_map.mpi

# Build rule for target.
ex.02.unordered_map.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.02.unordered_map.mpi
.PHONY : ex.02.unordered_map.mpi

# fast build rule for target.
ex.02.unordered_map.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.02.unordered_map.mpi.dir/build.make dash/CMakeFiles/ex.02.unordered_map.mpi.dir/build
.PHONY : ex.02.unordered_map.mpi/fast

#=============================================================================
# Target rules for targets named ex.03.globref.mpi

# Build rule for target.
ex.03.globref.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.03.globref.mpi
.PHONY : ex.03.globref.mpi

# fast build rule for target.
ex.03.globref.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.03.globref.mpi.dir/build.make dash/CMakeFiles/ex.03.globref.mpi.dir/build
.PHONY : ex.03.globref.mpi/fast

#=============================================================================
# Target rules for targets named ex.04.memalloc.mpi

# Build rule for target.
ex.04.memalloc.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.04.memalloc.mpi
.PHONY : ex.04.memalloc.mpi

# fast build rule for target.
ex.04.memalloc.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.04.memalloc.mpi.dir/build.make dash/CMakeFiles/ex.04.memalloc.mpi.dir/build
.PHONY : ex.04.memalloc.mpi/fast

#=============================================================================
# Target rules for targets named ex.05.min_element.mpi

# Build rule for target.
ex.05.min_element.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.05.min_element.mpi
.PHONY : ex.05.min_element.mpi

# fast build rule for target.
ex.05.min_element.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.05.min_element.mpi.dir/build.make dash/CMakeFiles/ex.05.min_element.mpi.dir/build
.PHONY : ex.05.min_element.mpi/fast

#=============================================================================
# Target rules for targets named ex.06.pattern-block-visualizer.mpi

# Build rule for target.
ex.06.pattern-block-visualizer.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.06.pattern-block-visualizer.mpi
.PHONY : ex.06.pattern-block-visualizer.mpi

# fast build rule for target.
ex.06.pattern-block-visualizer.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.06.pattern-block-visualizer.mpi.dir/build.make dash/CMakeFiles/ex.06.pattern-block-visualizer.mpi.dir/build
.PHONY : ex.06.pattern-block-visualizer.mpi/fast

#=============================================================================
# Target rules for targets named ex.06.pattern-visualizer.mpi

# Build rule for target.
ex.06.pattern-visualizer.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.06.pattern-visualizer.mpi
.PHONY : ex.06.pattern-visualizer.mpi

# fast build rule for target.
ex.06.pattern-visualizer.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.06.pattern-visualizer.mpi.dir/build.make dash/CMakeFiles/ex.06.pattern-visualizer.mpi.dir/build
.PHONY : ex.06.pattern-visualizer.mpi/fast

#=============================================================================
# Target rules for targets named ex.06.std-algo.mpi

# Build rule for target.
ex.06.std-algo.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.06.std-algo.mpi
.PHONY : ex.06.std-algo.mpi

# fast build rule for target.
ex.06.std-algo.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.06.std-algo.mpi.dir/build.make dash/CMakeFiles/ex.06.std-algo.mpi.dir/build
.PHONY : ex.06.std-algo.mpi/fast

#=============================================================================
# Target rules for targets named ex.07.locality.mpi

# Build rule for target.
ex.07.locality.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.07.locality.mpi
.PHONY : ex.07.locality.mpi

# fast build rule for target.
ex.07.locality.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.07.locality.mpi.dir/build.make dash/CMakeFiles/ex.07.locality.mpi.dir/build
.PHONY : ex.07.locality.mpi/fast

#=============================================================================
# Target rules for targets named ex.07.locality-group.mpi

# Build rule for target.
ex.07.locality-group.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.07.locality-group.mpi
.PHONY : ex.07.locality-group.mpi

# fast build rule for target.
ex.07.locality-group.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.07.locality-group.mpi.dir/build.make dash/CMakeFiles/ex.07.locality-group.mpi.dir/build
.PHONY : ex.07.locality-group.mpi/fast

#=============================================================================
# Target rules for targets named ex.07.locality-split.mpi

# Build rule for target.
ex.07.locality-split.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.07.locality-split.mpi
.PHONY : ex.07.locality-split.mpi

# fast build rule for target.
ex.07.locality-split.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.07.locality-split.mpi.dir/build.make dash/CMakeFiles/ex.07.locality-split.mpi.dir/build
.PHONY : ex.07.locality-split.mpi/fast

#=============================================================================
# Target rules for targets named ex.07.locality-threads.mpi

# Build rule for target.
ex.07.locality-threads.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.07.locality-threads.mpi
.PHONY : ex.07.locality-threads.mpi

# fast build rule for target.
ex.07.locality-threads.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.07.locality-threads.mpi.dir/build.make dash/CMakeFiles/ex.07.locality-threads.mpi.dir/build
.PHONY : ex.07.locality-threads.mpi/fast

#=============================================================================
# Target rules for targets named ex.08.io-hdf5.mpi

# Build rule for target.
ex.08.io-hdf5.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.08.io-hdf5.mpi
.PHONY : ex.08.io-hdf5.mpi

# fast build rule for target.
ex.08.io-hdf5.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.08.io-hdf5.mpi.dir/build.make dash/CMakeFiles/ex.08.io-hdf5.mpi.dir/build
.PHONY : ex.08.io-hdf5.mpi/fast

#=============================================================================
# Target rules for targets named ex.08.io-hdf5-stream.mpi

# Build rule for target.
ex.08.io-hdf5-stream.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.08.io-hdf5-stream.mpi
.PHONY : ex.08.io-hdf5-stream.mpi

# fast build rule for target.
ex.08.io-hdf5-stream.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.08.io-hdf5-stream.mpi.dir/build.make dash/CMakeFiles/ex.08.io-hdf5-stream.mpi.dir/build
.PHONY : ex.08.io-hdf5-stream.mpi/fast

#=============================================================================
# Target rules for targets named ex.09.view-1dim.mpi

# Build rule for target.
ex.09.view-1dim.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.09.view-1dim.mpi
.PHONY : ex.09.view-1dim.mpi

# fast build rule for target.
ex.09.view-1dim.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.09.view-1dim.mpi.dir/build.make dash/CMakeFiles/ex.09.view-1dim.mpi.dir/build
.PHONY : ex.09.view-1dim.mpi/fast

#=============================================================================
# Target rules for targets named ex.10.psort.mpi

# Build rule for target.
ex.10.psort.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.10.psort.mpi
.PHONY : ex.10.psort.mpi

# fast build rule for target.
ex.10.psort.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.10.psort.mpi.dir/build.make dash/CMakeFiles/ex.10.psort.mpi.dir/build
.PHONY : ex.10.psort.mpi/fast

#=============================================================================
# Target rules for targets named ex.10.radixsort.mpi

# Build rule for target.
ex.10.radixsort.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.10.radixsort.mpi
.PHONY : ex.10.radixsort.mpi

# fast build rule for target.
ex.10.radixsort.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.10.radixsort.mpi.dir/build.make dash/CMakeFiles/ex.10.radixsort.mpi.dir/build
.PHONY : ex.10.radixsort.mpi/fast

#=============================================================================
# Target rules for targets named ex.11.halo-stencil.mpi

# Build rule for target.
ex.11.halo-stencil.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.11.halo-stencil.mpi
.PHONY : ex.11.halo-stencil.mpi

# fast build rule for target.
ex.11.halo-stencil.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.11.halo-stencil.mpi.dir/build.make dash/CMakeFiles/ex.11.halo-stencil.mpi.dir/build
.PHONY : ex.11.halo-stencil.mpi/fast

#=============================================================================
# Target rules for targets named ex.11.simple-stencil.mpi

# Build rule for target.
ex.11.simple-stencil.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.11.simple-stencil.mpi
.PHONY : ex.11.simple-stencil.mpi

# fast build rule for target.
ex.11.simple-stencil.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.11.simple-stencil.mpi.dir/build.make dash/CMakeFiles/ex.11.simple-stencil.mpi.dir/build
.PHONY : ex.11.simple-stencil.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-mpi.mpi

# Build rule for target.
ex.12.simple-stencil-mpi.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-mpi.mpi
.PHONY : ex.12.simple-stencil-mpi.mpi

# fast build rule for target.
ex.12.simple-stencil-mpi.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-mpi.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-mpi.mpi.dir/build
.PHONY : ex.12.simple-stencil-mpi.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-mpi-openmp.mpi

# Build rule for target.
ex.12.simple-stencil-mpi-openmp.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-mpi-openmp.mpi
.PHONY : ex.12.simple-stencil-mpi-openmp.mpi

# fast build rule for target.
ex.12.simple-stencil-mpi-openmp.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-mpi-openmp.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-mpi-openmp.mpi.dir/build
.PHONY : ex.12.simple-stencil-mpi-openmp.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-mpi-openmptasks.mpi

# Build rule for target.
ex.12.simple-stencil-mpi-openmptasks.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-mpi-openmptasks.mpi
.PHONY : ex.12.simple-stencil-mpi-openmptasks.mpi

# fast build rule for target.
ex.12.simple-stencil-mpi-openmptasks.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-mpi-openmptasks.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-mpi-openmptasks.mpi.dir/build
.PHONY : ex.12.simple-stencil-mpi-openmptasks.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-notasks.mpi

# Build rule for target.
ex.12.simple-stencil-notasks.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-notasks.mpi
.PHONY : ex.12.simple-stencil-notasks.mpi

# fast build rule for target.
ex.12.simple-stencil-notasks.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-notasks.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-notasks.mpi.dir/build
.PHONY : ex.12.simple-stencil-notasks.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-omptasks.mpi

# Build rule for target.
ex.12.simple-stencil-omptasks.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-omptasks.mpi
.PHONY : ex.12.simple-stencil-omptasks.mpi

# fast build rule for target.
ex.12.simple-stencil-omptasks.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-omptasks.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-omptasks.mpi.dir/build
.PHONY : ex.12.simple-stencil-omptasks.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-tasks.mpi

# Build rule for target.
ex.12.simple-stencil-tasks.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-tasks.mpi
.PHONY : ex.12.simple-stencil-tasks.mpi

# fast build rule for target.
ex.12.simple-stencil-tasks.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-tasks.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-tasks.mpi.dir/build
.PHONY : ex.12.simple-stencil-tasks.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-tasks-copyin.mpi

# Build rule for target.
ex.12.simple-stencil-tasks-copyin.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-tasks-copyin.mpi
.PHONY : ex.12.simple-stencil-tasks-copyin.mpi

# fast build rule for target.
ex.12.simple-stencil-tasks-copyin.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-tasks-copyin.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-tasks-copyin.mpi.dir/build
.PHONY : ex.12.simple-stencil-tasks-copyin.mpi/fast

#=============================================================================
# Target rules for targets named ex.12.simple-stencil-tasks-outdep.mpi

# Build rule for target.
ex.12.simple-stencil-tasks-outdep.mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex.12.simple-stencil-tasks-outdep.mpi
.PHONY : ex.12.simple-stencil-tasks-outdep.mpi

# fast build rule for target.
ex.12.simple-stencil-tasks-outdep.mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/ex.12.simple-stencil-tasks-outdep.mpi.dir/build.make dash/CMakeFiles/ex.12.simple-stencil-tasks-outdep.mpi.dir/build
.PHONY : ex.12.simple-stencil-tasks-outdep.mpi/fast

#=============================================================================
# Target rules for targets named dash-test-mpi

# Build rule for target.
dash-test-mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dash-test-mpi
.PHONY : dash-test-mpi

# fast build rule for target.
dash-test-mpi/fast:
	$(MAKE) $(MAKESILENT) -f dash/CMakeFiles/dash-test-mpi.dir/build.make dash/CMakeFiles/dash-test-mpi.dir/build
.PHONY : dash-test-mpi/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f dash/testing/CMakeFiles/gtest.dir/build.make dash/testing/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f dash/testing/CMakeFiles/gtest_main.dir/build.make dash/testing/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... app.01.mindeg.mpi"
	@echo "... bench.01.igups.mpi"
	@echo "... bench.02.memhog.mpi"
	@echo "... bench.02.meminit.mpi"
	@echo "... bench.03.gups.mpi"
	@echo "... bench.04.histo-tf.mpi"
	@echo "... bench.04.histo.mpi"
	@echo "... bench.05.array-range.mpi"
	@echo "... bench.05.pattern.mpi"
	@echo "... bench.06.jacobi-1d.mpi"
	@echo "... bench.07.local-copy.mpi"
	@echo "... bench.08.min-element.mpi"
	@echo "... bench.08.transform.mpi"
	@echo "... bench.09.multi-reader.mpi"
	@echo "... bench.10.summa.mpi"
	@echo "... bench.11.hdf-io.mpi"
	@echo "... bench.12.for_each.mpi"
	@echo "... bench.13.allreduce.mpi"
	@echo "... bench.13.taskbench.mpi"
	@echo "... bench.14.accumulate.mpi"
	@echo "... bench.15.amsgqbench-omp.mpi"
	@echo "... bench.15.amsgqbench.mpi"
	@echo "... bench.15.copy.mpi"
	@echo "... dart-base"
	@echo "... dart-mpi"
	@echo "... dart-tasking"
	@echo "... dash-mpi"
	@echo "... dash-test-mpi"
	@echo "... ex.01.hello-mpi.mpi"
	@echo "... ex.01.hello.mpi"
	@echo "... ex.02.array-copy.mpi"
	@echo "... ex.02.array-csr.mpi"
	@echo "... ex.02.array-ctors.mpi"
	@echo "... ex.02.array-delayed.mpi"
	@echo "... ex.02.array-local.mpi"
	@echo "... ex.02.array.mpi"
	@echo "... ex.02.halo-swap.mpi"
	@echo "... ex.02.matrix-multiply.mpi"
	@echo "... ex.02.matrix.halo.heat_equation.dashtasks.blocked.mpi"
	@echo "... ex.02.matrix.halo.heat_equation.dashtasks.mpi"
	@echo "... ex.02.matrix.halo.heat_equation.mpi"
	@echo "... ex.02.matrix.mpi"
	@echo "... ex.02.matrix_distribution_patterns.mpi"
	@echo "... ex.02.matrix_global_access.mpi"
	@echo "... ex.02.matrix_printed_in_different_ways.mpi"
	@echo "... ex.02.matrix_views.mpi"
	@echo "... ex.02.unordered_map.mpi"
	@echo "... ex.03.globref.mpi"
	@echo "... ex.04.memalloc.mpi"
	@echo "... ex.05.min_element.mpi"
	@echo "... ex.06.pattern-block-visualizer.mpi"
	@echo "... ex.06.pattern-visualizer.mpi"
	@echo "... ex.06.std-algo.mpi"
	@echo "... ex.07.locality-group.mpi"
	@echo "... ex.07.locality-split.mpi"
	@echo "... ex.07.locality-threads.mpi"
	@echo "... ex.07.locality.mpi"
	@echo "... ex.08.io-hdf5-stream.mpi"
	@echo "... ex.08.io-hdf5.mpi"
	@echo "... ex.09.view-1dim.mpi"
	@echo "... ex.10.psort.mpi"
	@echo "... ex.10.radixsort.mpi"
	@echo "... ex.11.halo-stencil.mpi"
	@echo "... ex.11.simple-stencil.mpi"
	@echo "... ex.12.simple-stencil-mpi-openmp.mpi"
	@echo "... ex.12.simple-stencil-mpi-openmptasks.mpi"
	@echo "... ex.12.simple-stencil-mpi.mpi"
	@echo "... ex.12.simple-stencil-notasks.mpi"
	@echo "... ex.12.simple-stencil-omptasks.mpi"
	@echo "... ex.12.simple-stencil-tasks-copyin.mpi"
	@echo "... ex.12.simple-stencil-tasks-outdep.mpi"
	@echo "... ex.12.simple-stencil-tasks.mpi"
	@echo "... gtest"
	@echo "... gtest_main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

